apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-config
  namespace: portfolio
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "portfolio"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  APP_ENV: "production"
  APP_PORT: "8000"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRE_MINUTES: "1440"
